language: node_js
node_js: node
services:
- mongodb
deploy:
  provider: heroku
  api_key:
    secure: 02806104-080f-41fb-bb6f-26a8abe3815d
  app: vast-escarpment-84132
  on:
    repo: taivic/workout-app